// <auto-generated>
//     Generated code for PlayHouse Connector packet protocol
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;

namespace PlayHouse.Connector.Packet
{
    /// <summary>
    /// Client packet sent to server
    /// </summary>
    public sealed partial class ClientPacket : pb::IMessage<ClientPacket>
    {
        private static readonly pb::MessageParser<ClientPacket> _parser = new pb::MessageParser<ClientPacket>(() => new ClientPacket());
        private pb::UnknownFieldSet _unknownFields;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ClientPacket> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor => throw new global::System.NotImplementedException();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor => Descriptor;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ClientPacket()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ClientPacket(ClientPacket other) : this()
        {
            msgSeq_ = other.msgSeq_;
            msgId_ = other.msgId_;
            payload_ = other.payload_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ClientPacket Clone()
        {
            return new ClientPacket(this);
        }

        /// <summary>Field number for the "msg_seq" field.</summary>
        public const int MsgSeqFieldNumber = 1;
        private ushort msgSeq_;
        /// <summary>
        /// Message sequence number for request/response matching
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ushort MsgSeq
        {
            get { return msgSeq_; }
            set { msgSeq_ = value; }
        }

        /// <summary>Field number for the "msg_id" field.</summary>
        public const int MsgIdFieldNumber = 2;
        private ushort msgId_;
        /// <summary>
        /// Message type identifier
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ushort MsgId
        {
            get { return msgId_; }
            set { msgId_ = value; }
        }

        /// <summary>Field number for the "payload" field.</summary>
        public const int PayloadFieldNumber = 3;
        private pb::ByteString payload_ = pb::ByteString.Empty;
        /// <summary>
        /// Message payload
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pb::ByteString Payload
        {
            get { return payload_; }
            set { payload_ = value ?? pb::ByteString.Empty; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as ClientPacket);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ClientPacket other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (MsgSeq != other.MsgSeq) return false;
            if (MsgId != other.MsgId) return false;
            if (Payload != other.Payload) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (MsgSeq != 0) hash ^= MsgSeq.GetHashCode();
            if (MsgId != 0) hash ^= MsgId.GetHashCode();
            if (Payload.Length != 0) hash ^= Payload.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (MsgSeq != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(MsgSeq);
            }
            if (MsgId != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(MsgId);
            }
            if (Payload.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteBytes(Payload);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (MsgSeq != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgSeq);
            }
            if (MsgId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgId);
            }
            if (Payload.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ClientPacket other)
        {
            if (other == null)
            {
                return;
            }
            if (other.MsgSeq != 0)
            {
                MsgSeq = other.MsgSeq;
            }
            if (other.MsgId != 0)
            {
                MsgId = other.MsgId;
            }
            if (other.Payload.Length != 0)
            {
                Payload = other.Payload;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 8:
                        {
                            MsgSeq = (ushort)input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            MsgId = (ushort)input.ReadUInt32();
                            break;
                        }
                    case 26:
                        {
                            Payload = input.ReadBytes();
                            break;
                        }
                }
            }
        }
    }

    /// <summary>
    /// Server packet received from server
    /// </summary>
    public sealed partial class ServerPacket : pb::IMessage<ServerPacket>
    {
        private static readonly pb::MessageParser<ServerPacket> _parser = new pb::MessageParser<ServerPacket>(() => new ServerPacket());
        private pb::UnknownFieldSet _unknownFields;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ServerPacket> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor => throw new global::System.NotImplementedException();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor => Descriptor;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ServerPacket()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ServerPacket(ServerPacket other) : this()
        {
            msgSeq_ = other.msgSeq_;
            msgId_ = other.msgId_;
            errorCode_ = other.errorCode_;
            payload_ = other.payload_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ServerPacket Clone()
        {
            return new ServerPacket(this);
        }

        /// <summary>Field number for the "msg_seq" field.</summary>
        public const int MsgSeqFieldNumber = 1;
        private ushort msgSeq_;
        /// <summary>
        /// Message sequence number for request/response matching
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ushort MsgSeq
        {
            get { return msgSeq_; }
            set { msgSeq_ = value; }
        }

        /// <summary>Field number for the "msg_id" field.</summary>
        public const int MsgIdFieldNumber = 2;
        private ushort msgId_;
        /// <summary>
        /// Message type identifier
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ushort MsgId
        {
            get { return msgId_; }
            set { msgId_ = value; }
        }

        /// <summary>Field number for the "error_code" field.</summary>
        public const int ErrorCodeFieldNumber = 3;
        private ushort errorCode_;
        /// <summary>
        /// Error code (0 = success)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ushort ErrorCode
        {
            get { return errorCode_; }
            set { errorCode_ = value; }
        }

        /// <summary>Field number for the "payload" field.</summary>
        public const int PayloadFieldNumber = 4;
        private pb::ByteString payload_ = pb::ByteString.Empty;
        /// <summary>
        /// Message payload
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pb::ByteString Payload
        {
            get { return payload_; }
            set { payload_ = value ?? pb::ByteString.Empty; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as ServerPacket);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ServerPacket other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (MsgSeq != other.MsgSeq) return false;
            if (MsgId != other.MsgId) return false;
            if (ErrorCode != other.ErrorCode) return false;
            if (Payload != other.Payload) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (MsgSeq != 0) hash ^= MsgSeq.GetHashCode();
            if (MsgId != 0) hash ^= MsgId.GetHashCode();
            if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
            if (Payload.Length != 0) hash ^= Payload.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (MsgSeq != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(MsgSeq);
            }
            if (MsgId != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(MsgId);
            }
            if (ErrorCode != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(ErrorCode);
            }
            if (Payload.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteBytes(Payload);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (MsgSeq != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgSeq);
            }
            if (MsgId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgId);
            }
            if (ErrorCode != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ErrorCode);
            }
            if (Payload.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ServerPacket other)
        {
            if (other == null)
            {
                return;
            }
            if (other.MsgSeq != 0)
            {
                MsgSeq = other.MsgSeq;
            }
            if (other.MsgId != 0)
            {
                MsgId = other.MsgId;
            }
            if (other.ErrorCode != 0)
            {
                ErrorCode = other.ErrorCode;
            }
            if (other.Payload.Length != 0)
            {
                Payload = other.Payload;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 8:
                        {
                            MsgSeq = (ushort)input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            MsgId = (ushort)input.ReadUInt32();
                            break;
                        }
                    case 24:
                        {
                            ErrorCode = (ushort)input.ReadUInt32();
                            break;
                        }
                    case 34:
                        {
                            Payload = input.ReadBytes();
                            break;
                        }
                }
            }
        }
    }
}

#endregion

#pragma warning restore 1591, 0612, 3021, 8981
